### ISSUE TITLE
error reporting when template is not found

### ISSUE THREAD

**Issue by dbu** [smartive/SmartiveHandlebarsBundle#4]
currently when a handlebars template is not found, i get :  ContextErrorException: Warning: Missing argument 2 for Symfony\Bridge\Twig\Extension\HttpKernelExtension::renderFragmentStrategy()

i am not sure if this is related to me calling a custom twig extension that tries to call "Smartive\HandlebarsBundle\Templating\Renderer::render" or if the exception would always come at that place. feels a bit strange that the twig bridge should be involved with the error...

**Comment by mfeltscher** [comment]
@dbu I'm not able to reproduce this. When using `Smartive\HandlebarsBundle\Templating\Renderer::render` inside a Twig extension I get a `InvalidArgumentException` stating that the template cannot be found. Could you please share your Twig extension code so I can try to reproduce this?

**Comment by dbu** [comment]
ok, can't reproduce but while trying produced some functional tests: #6.
