### ISSUE TITLE
php 5.3

### ISSUE THREAD

**Issue by waltercruz** [smartive/SmartiveHandlebarsBundle#8]
Any reasons to require php 5.5? I would like to use with php 5.4 or even 5.3

**Comment by mfeltscher** [comment]
I will give it a try on 5.3 and will let you know, if that would be working.

**Comment by mfeltscher** [comment]
@waltercruz Unfortunately I don't have a PHP 5.3 installation which I could test this on. You can test it yourself by forking the repository, changing the minimum version to 5.3 in `composer.json`, and adding the following configuration to your local `composer.json` file:

``` json
"repositories": [
    {
        "type": "vcs",
        "url": "git@github.com:waltercruz/SmartiveHandlebarsBundle.git"
    }
]
```

If your tests are successful create a pull request and let me know.

Thanks

**Comment by mfeltscher** [comment]
Starting with version 1.0.0, PHP 5.3 support has officially been dropped.
