### ISSUE TITLE
Option to use StringLoader

### ISSUE THREAD

**Issue by montaniasystemab** [smartive/SmartiveHandlebarsBundle#9]
First off thanks for a useful bundle!

I need an option to use the `StringLoader` instead of `FilesystemLoader`.

My use case is a mix of loading templates from disk and from strings, so it would be useful to be able to easily switch between the two.

I could submit a PR but would like to discuss how to best implement the option. 

Multiple methods on the `Renderer` object? 

Multiple services in the container?

Any other idea? 

I'll just use the `Handlebars\Handlebars` class for now which defaults to `StringLoader`

**Comment by montaniasystemab** [comment]
Maybe there isn't at all a use case for the `StringLoader` in the bundle since it would basically only proxy calls to an object that you could just instantiate yourself with `new Handlebars()`.

What do you think? Just injecting two objects might be the correct way to solve it after all.

**Comment by mfeltscher** [comment]
Hi @montaniasystemab 

Thank you for your feedback!

I don't see the point of having such a proxy method either. Just use `Handlebars\Handlebars` and you should be fine. :)

**Comment by montaniasystemab** [comment]
Yes, just had to try it to realize that's a good solution. Sorry for taking up your time but at least i got the chance to thank you for your bundle =)
